sudo: false

matrix:
  include:
    - language: r
      warnings_are_errors: true
      cache:
        packages: true
    - language: python
      install:
        - pip install -e python/. --user

os:
  - linux
