sudo: false

repos:
  CRAN: http://cran.rstudio.com/

matrix:
  include:
    - name: "R (3.2.3)"
      language: r
      r: 3.2.3
      warnings_are_errors: true
      cache:
        packages: true
      script:
        - |
          R CMD build --resave-data .
          R CMD check --no-build-vignettes --no-manual pins*tar.gz
    - name: "R (release)"
      language: r
      r: release
      warnings_are_errors: true
      r_packages:
        - covr
      cache:
        packages: true
      script:
        - |
          R CMD build --resave-data .
          R CMD check --no-build-vignettes --no-manual pins*tar.gz
      after_success:
        - rm -rf ~/.pins
        - Rscript -e 'covr::codecov()'
    - name: "Python"
      language: r
      r_packages:
        - feather
      before_install:
        - export LD_LIBRARY_PATH="/home/travis/R-bin/lib/R/lib:$LD_LIBRARY_PATH"
        - pip install pandas --user
        - pip install pytest --user
        - pip install feather-format --user
        - pip install -e python/. --user
      script:
        - R CMD build --no-build-vignettes .
        - pytest python/pins/tests/test.py

os:
  - linux
