sudo: false

repos:
  CRAN: http://cran.rstudio.com/

language: r

cache:
  packages: true

matrix:
  include:
    - name: "R"
      r: 3.2.3
      warnings_are_errors: true
      r_packages:
        - tibble
        - covr
      script:
        - |
          R CMD build --resave-data .
          R CMD check --no-build-vignettes --no-manual --no-tests pins*tar.gz
          Rscript ci/travis.R
      env:
        -TEST_GITHUB_BRANCH="travis_old"
      after_success:
        - rm -rf ~/.pins
        - Rscript -e 'covr::codecov()'
    - name: "Python"
      r_packages:
        - feather
        - tibble
      before_install:
        - export LD_LIBRARY_PATH="/home/travis/R-bin/lib/R/lib:$LD_LIBRARY_PATH"
        - pip install pandas --user
        - pip install pytest --user
        - pip install feather-format --user
        - pip install -e python/. --user
      script:
        - R CMD build --no-build-vignettes .
        - Rscript -e 'install.packages(dir(".", pattern = "pins_"))'
        - pytest python/pins/tests/test.py
os:
  - linux
