sudo: false

matrix:
  include:
    - name: "R"
      language: r
      warnings_are_errors: true
      cache:
        packages: true
    - name: "Python"
      language: r
      before_install:
        - pip install -e python/. --user
        - pip install pandas --user
        - pip install pytest --user
      script:
        - pytest python/pins/tests/test.py

os:
  - linux
