sudo: false

matrix:
  include:
    - name: "R"
      language: r
      warnings_are_errors: true
      cache:
        packages: true
      script:
        - |
          R CMD build --resave-data .
          R CMD check --no-build-vignettes --no-manual pins*tar.gz

    - name: "Python"
      language: r
      before_install:
        - pip install -e python/. --user
        - pip install pandas --user
        - pip install pytest --user
      script:
        - pytest python/pins/tests/test.py

os:
  - linux
